# Base configs
baseurl: "https://isaacullah.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-55626306-1"

# UI configs
title: "Isaac Ullah, Photography."
subtitle: "Landscapes, seascapes, and travel."
author: "Isaac Ullah"
header: 
 title: "Landscapes, seascapes, and travel."
 subtitle: "by Isaac Ullah"
footer:
 bio: "I am an archaeologist, world traveler, and lover of the outdoors. I take photos of my travels, of nature, and of details in the built environment."
 copyright: "All images Copyright Isaac Ullah, 2018"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/isaacullah"
  twitter: "https://www.twitter.com/isaacullah"
  github: "https://www.github.com/isaacullah"
  pixls: "https://discuss.pixls.us/u/Isaac"
  flickr: "https://www.flickr.com/isaacullah"
